paths:
  /api/products:
    get:
      summary: Get all products
      tags: 
        - Products
      responses: 
        "200":
          description: Products obtained successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "400":
          description: Cannot obtain Products
  
  /api/products/{pid}:
    get:
      summary: Get one product by id
      tags: 
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: user id provided for search
        schema:
          $type: ObjectId
      responses: 
        "200":
          description: Product obtained successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        "400":
          description: Cannot obtain Product

components:
  schemas:
    Products:
      type: object
      properties: 
        _id:
          type: string
          description: Mongo's autogenerated ID
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        price:          
          type: number
          description: Product price
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product stock
        status:
          type: boolean
          description: Product status
        category:
          type: string
          description: Product category
        thumbnail:
          type: string
          description: Product thumbnail
        owner:
          type: string
          description: ADMIN or email of product owner
      example:
        _id: "ObjectId('6626fb05db8bd92a770fc580')"
        title: product title
        description: product description
        price: 20
        code: abc123
        stock: 4
        status: true
        category: cat 2
        thumbnail: thumbnail_url
        owner: premium@user.com
